refresh_rate: 1 seconds
appenders:
  stdout:
    kind: file
    path: "log/log.log"
    encoder:
      pattern: "{d} - {m} - {n} - {L}"
root:
  level: warn
  appenders:
    - stdout
loggers:
  app::backend::db:
    level: info
  app::requests:
    level: info
    appenders:
      - requests
    additive: false